services:
  - type: static
    name: aimall-frontend
    env: static
    buildCommand: npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
